---
- hosts: openstack
  gather_facts: no
  become: no
  tasks:
    - include_tasks: tasks/deploy-openstack.yml

    - name: add os instance ip into host group builder
      add_host:
        name: "{{ instance_result.openstack.public_v4 }}"
        groups: builder
        builder_ip: "{{ instance_result.openstack.public_v4 }}"

- hosts: builder
  tasks:
    - include_tasks: tasks/build-ostree-image-ng.yml

    - name: add builder ip and ostree commit into host group beaker
      add_host:
        name: localhost
        groups: beaker
        builder_ip: "{{ builder_ip }}"
        ostree_commit: "{{ ostree_commit }}"

- hosts: beaker
  gather_facts: no
  become: no
  tasks:
    - include_tasks: tasks/beaker-install.yml

    - name: add beaker server hostname into host group ostree
      add_host:
        name: "{{ ostree_hostname }}"
        groups: ostree
        ostree_commit: "{{ ostree_commit }}"
        builder_ip: "{{ builder_ip }}"
        ostree_hostname: "{{ ostree_hostname }}"

- hosts: ostree
  vars:
    total_counter: "0"
    failed_counter: "0"
  vars_files:
    - "{{ playbook_dir }}/files/allowed_errors.yml"
  tasks:
    - set_fact:
        ostree_hostname: "{{ ostree_hostname }}"

    - include_tasks: tasks/check-ostree-bare-ng.yml

    - name: add os instance ip into host group builder
      add_host:
        name: "{{ builder_ip }}"
        groups: builder
        ostree_hostname: "{{ ostree_hostname }}"

- hosts: builder
  tasks:
    - include_tasks: tasks/build-upgrade-image-ng.yml

    - name: add os instance ip into host group builder
      add_host:
        name: "{{ ostree_hostname }}"
        groups: ostree
        ostree_commit: "{{ ostree_commit }}"

- hosts: ostree
  vars:
    total_counter: "0"
    failed_counter: "0"
    ostree_upgrade: "true"
  tasks:
    - name: update latest ostree commit
      shell: |
        ostree remote delete rhel-edge
        ostree remote add --no-gpg-verify --no-sign-verify rhel-edge http://{{ builder_ip }}/repo
      become: yes
      register: result_update

    - name: update latest ostree commit
      command: rpm-ostree update
      become: yes
      register: result_update

    - name: reboot to deploy new ostree commit
      reboot:
      become: yes

    - name: waits until instance is reachable
      wait_for:
        host: "{{ ostree_hostname }}"
        port: 22
        search_regex: OpenSSH
        delay: 10
        timeout: 1200

    - include_tasks: tasks/check-ostree-bare-ng.yml
    - include_tasks: tasks/check-greenboot.yml

    # reboot again to test no things changed
    - name: reboot again and no commit change
      reboot:
        connect_timeout: 1800
      become: yes

    - name: waits until instance is reachable
      wait_for:
        host: "{{ ostree_hostname }}"
        port: 22
        search_regex: OpenSSH
        delay: 10

    - include_tasks: tasks/check-ostree-bare-ng.yml
