pipeline {
    agent none
    environment {
        GCN_URL = credentials('google-chat-rhel-edge-url')
        TRIGGERED_BY = get_triggered_by()
    }

    stages {
        stage('Preparing') {
            when {
                beforeAgent true
                environment name: 'TRIGGERED_BY', value: 'Triggered by CI message.'
            }
            agent { label 'container-fedora-33-prod' }
            steps {
                script {
                    env.COMPOSE_ID = sh(returnStdout: true, script: 'echo $CI_MESSAGE | /usr/bin/jq -r ".compose_id"').trim()
                    currentBuild.displayName = "${env.BUILD_NUMBER}-${env.COMPOSE_ID}"
                    env.RELEASE_VERSION = sh(returnStdout: true, script: 'echo $CI_MESSAGE | /usr/bin/jq -r ".release_version"').trim()
                }
            }
        }
        stage('Testing') {
            parallel {
                stage('EL8.3 Virt') {
                    when {
                        beforeAgent true
                        anyOf {
                            anyOf {
                                environment name: 'TRIGGERED_BY', value: 'Branch indexing'
                                expression { return env.TRIGGERED_BY.matches("Pull request(.*)") }
                            }
                            allOf {
                                environment name: 'TRIGGERED_BY', value: 'Triggered by CI message.'
                                anyOf {
                                    environment name: 'RELEASE_VERSION', value: '8.3.0'
                                    environment name: 'RELEASE_VERSION', value: '8.3.1'
                                }
                            }
                        }
                    }
                    agent { label 'vm-rhel-8-3-1' }
                    environment {
                        TEST_OS = "rhel-8-3"
                    }
                    steps {
                        run_virt_test('ostree-legacy')
                    }
                    post {
                        always {
                            preserve_logs()
                            get_package_info()
                            send_result('Virt-KVM')
                        }
                    }
                }
                stage('EL8.4 Virt') {
                    when {
                        beforeAgent true
                        anyOf {
                            anyOf {
                                environment name: 'TRIGGERED_BY', value: 'Branch indexing'
                                expression { return env.TRIGGERED_BY.matches("Pull request(.*)") }
                            }
                            allOf {
                                environment name: 'TRIGGERED_BY', value: 'Triggered by CI message.'
                                anyOf {
                                    environment name: 'RELEASE_VERSION', value: '8.4.0'
                                    environment name: 'RELEASE_VERSION', value: '8.4.1'
                                }
                            }
                        }
                    }
                    agent { label 'vm-rhel-8-4-0' }
                    environment {
                        TEST_OS = "rhel-8-4"
                    }
                    steps {
                        run_virt_test('ostree-legacy')
                    }
                    post {
                        always {
                            preserve_logs()
                            get_package_info()
                            send_result('Virt-KVM')
                        }
                    }
                }
                stage('EL8.4 ng Virt') {
                    when {
                        beforeAgent true
                        anyOf {
                            anyOf {
                                environment name: 'TRIGGERED_BY', value: 'Branch indexing'
                                expression { return env.TRIGGERED_BY.matches("Pull request(.*)") }
                            }
                            allOf {
                                environment name: 'TRIGGERED_BY', value: 'Triggered by CI message.'
                                anyOf {
                                    environment name: 'RELEASE_VERSION', value: '8.4.0'
                                    environment name: 'RELEASE_VERSION', value: '8.4.1'
                                }
                            }
                        }
                    }
                    agent { label 'vm-rhel-8-4-0' }
                    environment {
                        TEST_OS = "rhel-8-4"
                    }
                    steps {
                        run_virt_test('ostree-ng')
                    }
                    post {
                        always {
                            preserve_logs()
                            get_package_info()
                            send_result('Virt-NG-KVM')
                        }
                    }
                }
                stage('EL8.4 Bare') {
                    when {
                        beforeAgent true
                        anyOf {
                            anyOf {
                                environment name: 'TRIGGERED_BY', value: 'Branch indexing'
                                expression { return env.TRIGGERED_BY.matches("Pull request(.*)") }
                            }
                            allOf {
                                environment name: 'TRIGGERED_BY', value: 'Triggered by CI message.'
                                anyOf {
                                    environment name: 'RELEASE_VERSION', value: '8.4.0'
                                    environment name: 'RELEASE_VERSION', value: '8.4.1'
                                }
                            }
                        }
                    }
                    agent { label 'container-fedora-33-prod' }
                    environment {
                        TEST_OS = "rhel-8-4"
                        ARCH = 'x86_64'
                    }
                    steps {
                        run_bare_test('ostree-legacy')
                    }
                    post {
                        always {
                            preserve_logs()
                            send_result('Bare-metal-beaker')
                        }
                    }
                }
                stage('EL8.4 ng Bare') {
                    when {
                        beforeAgent true
                        anyOf {
                            anyOf {
                                environment name: 'TRIGGERED_BY', value: 'Branch indexing'
                                expression { return env.TRIGGERED_BY.matches("Pull request(.*)") }
                            }
                            allOf {
                                environment name: 'TRIGGERED_BY', value: 'Triggered by CI message.'
                                anyOf {
                                    environment name: 'RELEASE_VERSION', value: '8.4.0'
                                    environment name: 'RELEASE_VERSION', value: '8.4.1'
                                }
                            }
                        }
                    }
                    agent { label 'container-fedora-33-prod' }
                    environment {
                        TEST_OS = "rhel-8-4"
                        ARCH = 'x86_64'
                    }
                    steps {
                        run_bare_test('ostree-ng')
                    }
                    post {
                        always {
                            preserve_logs()
                            send_result('Bare-metal-beaker')
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            script {
                print(currentBuild.getBuildCauses()[0])
            }
        }
    }
    options {
        timestamps()
        timeout(time: 3, unit: 'HOURS')
    }
}

void get_triggered_by() {
    return currentBuild.getBuildCauses()[0].shortDescription
}

void run_virt_test(test_type) {
    sh label: 'wait until cloud-init done', script: """
        while true; do
            test -f /var/lib/cloud/instance/boot-finished && break
        done
        printenv
    """

    if (test_type == 'ostree-ng') {
        withCredentials([usernamePassword(credentialsId: 'quay-io-credential', passwordVariable: 'QUAY_PASSWORD', usernameVariable: 'QUAY_USERNAME')]) {
            sh "./ostree-ng.sh"
        }
    }
    if (test_type == 'ostree-legacy') {
        sh "./ostree.sh"
    }
}

void run_bare_test(test_type) {
    sh "ansible-galaxy collection install containers.podman"
    if (test_type == 'ostree-ng') {
        withCredentials([string(credentialsId: 'ansible-vault-password', variable: 'VAULT_PASSWORD')]) {
            sh label: 'run ansible playbook', script: """
                printenv
                ansible-playbook -v -i inventory ostree-bare-ng.yml
            """
        }
    }
    if (test_type == 'ostree-legacy') {
        withCredentials([string(credentialsId: 'ansible-vault-password', variable: 'VAULT_PASSWORD')]) {
            sh label: 'run ansible playbook', script: """
                printenv
                ansible-playbook -v -i inventory ostree-bare.yml
            """
        }
    }
}

void preserve_logs() {
    archiveArtifacts allowEmptyArchive: true, artifacts: 'osbuild-*.log'
    archiveArtifacts allowEmptyArchive: true, artifacts: 'osbuild-*.json'
}

void send_result(test_type) {
    script {
        if (env.TRIGGERED_BY == 'Triggered by CI message.') {
            googlechatnotification message: "${currentBuild.currentResult}\nCompose: ${env.COMPOSE_ID}\nPackages: ${env.PACKAGE_INFO}\nTest Env: ${test_type}\nConsole Log: ${env.BUILD_URL}display/redirect",
                                   notifyAborted: true,
                                   notifyFailure: true,
                                   notifyNotBuilt: true,
                                   notifySuccess: true,
                                   url: "${env.GCN_URL}"
        }
    }
}

void get_package_info() {
    script {
        env.PACKAGE_INFO = sh(returnStdout: true, script: 'rpm -qa | grep -E "osbuild|composer-cli"').trim()
    }
}
