#!/bin/bash
set -ex

if [ "$#" -lt 2 ]; then
    echo >&2 "Usage: virt-install-ostree IMAGE KICKSTART OS URL"
    exit 1
fi

out=$1
ks=$2
os=$3
url=$4

qemu-img create -f qcow2 "$out" 20G

supervised_virt_install () {
expect -- - virt-install "$@" <<'EOF'
eval spawn $argv
set timeout -1
expect {
  "emergency mode" { send_user "\n\n\n\nABORT - emergency shell\n"
                     exit 1
                   }
  "Please make your choice" { send_user "\n\n\n\nABORT - Anaconda stopped\n"
                              exit 1
                            }
  "Please make a selection" { send_user "\n\n\n\nABORT - Anaconda stopped\n"
                              exit 1
                            }
}
EOF
}

case $os in
    "fedora-32")
        os_variant="fedora32";;
    "rhel-8-3")
        os_variant="rhel8.2";;
    *) ;;
esac

supervised_virt_install --initrd-inject="$ks" \
                        --extra-args="ks=file:/$ks console=ttyS0,115200" \
                        --name="ostree-guest" \
                        --disk "path=$out,format=qcow2" \
                        --ram 4096 \
                        --vcpus=1 \
                        --network bridge=ostree,mac=52:54:00:54:07:11 \
                        --os-type linux \
                        --os-variant $os_variant \
                        --location="$url" \
                        --nographics \
                        --noreboot

