FROM quay.io/fedora/fedora:37-aarch64

LABEL name="ansible_runner" \
      maintainer="xiaofwan@redhat.com" \
      version="1" \
      release="1" \
      description="Run Ansible inside container"

RUN dnf -y update && \
    dnf -y install \
        openssh-clients \
        ansible-core \
        curl \
        net-tools \
        python3 && \
    dnf clean all && \
    ansible-galaxy collection install community.general

WORKDIR /work
