---
kind: Template
apiVersion: v1
labels:
  app: ocp4-sa-edit-token
  template: ocp4-sa-edit-token-template
metadata:
  name: ocp4-sa-edit-token
  annotations:
    tags: token, ocp4

objects:
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: sa-edit-token
  - kind: RoleBinding
    apiVersion: v1
    metadata:
      name: sa-edit-token-edit
    groupNames:
    subjects:
      - kind: ServiceAccount
        name: sa-edit-token
    roleRef:
      name: edit
