---
name: Build and upload ansible runner container

on:
  workflow_dispatch:
  schedule:
    # run 8:05 every Sunday
    - cron: '5 8 * * 0'

jobs:
  build-upload:
    # Do not run this job on any fork repos
    if: github.repository == 'virt-s1/rhel-edge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build container
        run: |
          sudo apt-get install -y podman
          podman build -t ansible-runner:x86_64 -f tools/Dockerfile.ansible.x86_64
          podman push --creds "$QUAY_USERNAME":"$QUAY_PASSWORD" ansible-runner:x86_64 quay.io/rhel-edge/ansible-runner:x86_64
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
