---
name: FDO container test trigger

on:
  workflow_dispatch:
  schedule:
    # run 8:05 every Sunday
    - cron: '5 8 * * 0'
    # run 8:05 every Thursday
    - cron: '5 8 * * 4'
    # run every day
    - cron: '0 3 * * *'

jobs:
  fdo-container-community:
    if: github.repository == 'virt-s1/rhel-edge' && github.event.schedule == '5 8 * * 0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make change for PR creating
        run: |
          echo "fdo-container" > fdo-container.run

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "FDO community container test - ${{ steps.date.outputs.date }}"
          committer: cloudkitebot <henrywangxf1@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: cpr
          branch-suffix: random
          delete-branch: true
          title: "FDO community container test - ${{ steps.date.outputs.date }}"
          labels: DO_NOT_MERGE,fdo-container
          body: |
            FDO community container test
            - Date: ${{ steps.date.outputs.date }}

      - name: Add a comment to trigger test workflow
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT }}
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
          body: /test-fdo-container-community

  fdo-container-official:
    if: github.repository == 'virt-s1/rhel-edge' && github.event.schedule == '5 8 * * 4'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make change for PR creating
        run: |
          echo "fdo-container" > fdo-container.run

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "FDO official container test - ${{ steps.date.outputs.date }}"
          committer: cloudkitebot <henrywangxf1@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: cpr
          branch-suffix: random
          delete-branch: true
          title: "FDO official container test - ${{ steps.date.outputs.date }}"
          labels: DO_NOT_MERGE,fdo-container
          body: |
            FDO official container test
            - Date: ${{ steps.date.outputs.date }}

      - name: Add a comment to trigger test workflow
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT }}
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
          body: /test-fdo-container-official
