---
name: ARM64 Edge RHEL 9.2.0 test trigger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1,3,5'

env:
  COMPOSE_URL_93: "http://${{ secrets.DOWNLOAD_NODE }}/rhel-9/nightly/RHEL-9"
  COMPOSE_URL_92: "http://${{ secrets.DOWNLOAD_NODE }}/rhel-9/nightly/updates/RHEL-9"

jobs:
  check-compose:
    # Do not run this job on any fork repos
    if: github.repository == 'virt-s1/rhel-edge'
    runs-on: [kite, x86_64, rhos-01, fedora-37, small]
    steps:
      - uses: actions/checkout@v3

      - name: Check RHEL 9.2 compose
        id: check_compose_id_92
        run: |
          curl -s ${COMPOSE_URL_92}/latest-RHEL-9.2.0/STATUS --output STATUS_92
          STATUS_92=$(cat STATUS_92)
          if [[ "$STATUS_92" == "FINISHED" ]]; then
              curl -s ${COMPOSE_URL_92}/latest-RHEL-9.2.0/COMPOSE_ID --output COMPOSE_ID_92
              COMPOSE_ID_92=$(cat COMPOSE_ID_92)
          else
              COMPOSE_ID_92="false"
          fi

          if [[ "$COMPOSE_ID_92" != "false" ]]; then
              OSBUILD_VERSION_92=$(curl -s "${COMPOSE_URL_92}/${COMPOSE_ID_92}/compose/AppStream/aarch64/os/Packages/" | grep -ioE ">osbuild-[0-9].*<" | tr -d "><")
              OSBUILD_COMPOSER_VERSION_92=$(curl -s "${COMPOSE_URL_92}/${COMPOSE_ID_92}/compose/AppStream/aarch64/os/Packages/" | grep -ioE ">osbuild-composer-[0-9].*<" | tr -d "><")
              COMPOSER_CLI_VERSION_92=$(curl -s "${COMPOSE_URL_92}/${COMPOSE_ID_92}/compose/AppStream/aarch64/os/Packages/" | grep -ioE ">weldr-client-[0-9].*<" | tr -d "><")
              echo "osbuild_version_92=$OSBUILD_VERSION_92" >> $GITHUB_OUTPUT
              echo "osbuild_composer_version_92=$OSBUILD_COMPOSER_VERSION_92" >> $GITHUB_OUTPUT
              echo "composer_cli_version_92=$COMPOSER_CLI_VERSION_92" >> $GITHUB_OUTPUT
          else
              echo "osbuild_version_92=Null" >> $GITHUB_OUTPUT
              echo "osbuild_composer_version_92=Null" >> $GITHUB_OUTPUT
              echo "composer_cli_version_92=Null" >> $GITHUB_OUTPUT
          fi

          echo "rhel92_compose=$COMPOSE_ID_92" >> $GITHUB_OUTPUT

    outputs:
      rhel92_compose: ${{ steps.check_compose_id_92.outputs.rhel92_compose }}
      osbuild_version_92: ${{ steps.check_compose_id_92.outputs.osbuild_version_92 }}
      osbuild_composer_version_92: ${{ steps.check_compose_id_92.outputs.osbuild_composer_version_92 }}
      composer_cli_version_92: ${{ steps.check_compose_id_92.outputs.composer_cli_version_92 }}

  arm-rhel92:
    needs: check-compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make change for PR creating
        run: |
          compose_id="${{ needs.check-compose.outputs.rhel92_compose }}"
          echo $compose_id >> arm_rhel92.run

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "aarch64 - ${{ needs.check-compose.outputs.rhel92_compose }} - ${{ steps.date.outputs.date }}"
          committer: cloudkitebot <henrywangxf1@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: cpr
          branch-suffix: random
          delete-branch: true
          title: "[aarch64] ${{ needs.check-compose.outputs.rhel92_compose }} - ${{ steps.date.outputs.date }}"
          labels: DO_NOT_MERGE,RHEL-9.2.0,aarch64
          body: |
            RHEL 9.2 compose ${{ needs.check-compose.outputs.rhel92_compose }}
            - Date: ${{ steps.date.outputs.date }}
            - Compose URL: "${{ env.COMPOSE_URL_92 }}/${{ needs.check-compose.outputs.rhel92_compose }}"
            - Packages:
                - ${{ needs.check-compose.outputs.osbuild_version_92 }}
                - ${{ needs.check-compose.outputs.osbuild_composer_version_92 }}
                - ${{ needs.check-compose.outputs.composer_cli_version_92 }}

      - name: Add a comment to trigger test workflow
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT }}
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
          body: /arm-rhel-9-2-all

      - name: Create a project card to track compose test result
        uses: peter-evans/create-or-update-project-card@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project-name: RHEL Compose Test
          column-name: RHEL-9-2
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
